"""
Central types module for the loksabha application.

This module provides a single import point for all types used across the application,
organized by domain but accessible from a central location to avoid circular imports.
"""

# Import everything explicitly instead of using star imports
from .models import (
    STATE_ORDER,
    VALID_TRANSITIONS,
    BaseProgressFileStructure,
    ChunkingData,
    CombinedResults,
    ExtractionResult,
    ExtractionSummary,
    GenericStateData,
    InitializedData,
    IssueFlag,
    LlmExtractionData,
    LlmExtractionPageData,
    LocalExtractionData,
    LocalExtractionPageData,
    ManualReviewData,
    ManualReviewPageData,
    ManualReviewTableData,
    MultiPageTableDetectionResult,
    MultiPageTableExtractionResults,
    MultiPageTableInfo,
    MultiPageTableResult,
    PageData,
    PageIdentifier,
    PageNumber,
    PageProcessingData,
    PageRange,
    PrepareDataData,
    ProcessingMetadata,
    ProcessingState,
    ProcessingStatus,
    ProgressFileStructure,
    QuestionProcessingProgressStateData,
    SinglePageTableResult,
    StateTransition,
    StateTransitionValidator,
    TableDetectionResult,
    TableMetadata,
    TableResult,
    TableSummary,
    TableType,
)
from .types import (
    FailedQuestionDownload,
    ParliamentQuestion,
    ParliamentQuestionsPipelineState,
    QuestionMetaAnalysis,
    QuestionPipelineState,
    QuestionType,
)

# Export everything so users can import from apps.py.types without worrying about internal file structure
__all__ = [
    # From types.py (Parliament Questions)
    "QuestionType",
    "ParliamentQuestion",
    "QuestionMetaAnalysis",
    "ParliamentQuestionsPipelineState",
    "QuestionPipelineState",
    "FailedQuestionDownload",
    # From models.py (Documents and Progress Tracking)
    "BaseProgressFileStructure",
    "MultiPageTableInfo",
    "ExtractionResult",
    "MultiPageTableResult",
    "SinglePageTableResult",
    "ExtractionSummary",
    "PageNumber",
    "PageRange",
    "PageIdentifier",
    "TableResult",
    "CombinedResults",
    "TableDetectionResult",
    "MultiPageTableDetectionResult",
    "TableSummary",
    "MultiPageTableExtractionResults",
    "ProcessingState",
    "ProcessingStatus",
    "TableMetadata",
    "IssueFlag",
    "ProcessingMetadata",
    "InitializedData",
    "LocalExtractionPageData",
    "LocalExtractionData",
    "LlmExtractionPageData",
    "ManualReviewPageData",
    "PageData",
    "LlmExtractionData",
    "ManualReviewData",
    "PageProcessingData",
    "PrepareDataData",
    "ChunkingData",
    "GenericStateData",
    "ProgressFileStructure",
    "QuestionProcessingProgressStateData",
    "StateTransition",
    "VALID_TRANSITIONS",
    "STATE_ORDER",
    "StateTransitionValidator",
    "ManualReviewTableData",
    "TableType",
]
